### ISSUE TITLE
how can I get he linode's public ipv6 address?

### ISSUE THREAD

**Issue by lfxc** [webinarium/linode-api3#5]
I can get the ipv4 address just fine, but can;t seem to figure out how to get the v6 address.

thanks!

**Comment by webinarium** [comment]
Seems it's not possible using Linode API - it returns only ipv4 addresses. Please remember, this library is only a wrap for Linode's API - the library just reflects the API abilities with all existing restrictions.

From another hand, the library wraps the APIv3, which is going to be replaced by new APIv4 soon (https://developers.linode.com/v4/reference/endpoints/linode/instances/:id/ips). Sorry, I haven't completed the library for APIv4 yet, but you can try to use the APIv4 manually and check - maybe the new API returns ipv6 now. Please be aware that APIv4 is still in beta, updates often, and may introduce BC changes btw its versions.

**Comment by webinarium** [comment]
Being curious, I have just tried their APIv4 using curl. First I've created an access token in the new Linode Manager (see https://developers.linode.com/v4/guides/curl/testing-with-curl) providing this token with "view only" access to everything.

No matter the token has access to all the endpoints, it's failed with "Your OAuth token is not authorized to use this endpoint" message when I tried the following (assume `$token` and `$id` are real token and Linode ID):
`curl -H "Authorization: token $token" https://api.linode.com/v4/linode/instances/$id/ips`

But the upper level endpoint worked fine and returned ipv6 as well:
`curl -H "Authorization: token $token" https://api.linode.com/v4/linode/instances/$id`

```js
{
    "group": "",
    "transfer_total": 1000,
    "vcpus": 1,
    "region": "us-west-1a",
    "distribution": "linode/ubuntu16.04lts",
    "updated": "2017-09-01T11:25:19",
    "created": "2017-09-01T07:27:33",
    "ipv4": ["192.168.xxx.xxx", "45.79.xxx.xxx"],
    "status": "running",
    "alerts": {
        "transfer_out": 10,
        "io": 10000,
        "cpu": 90,
        "transfer_quota": 80,
        "transfer_in": 10
    },
    "backups": {
        "enabled": false,
        "schedule": {
            "window": null,
            "day": null
        }
    },
    "id": 1234567,
    "label": "...",
    "memory": 1024,
    "ipv6": "xxxx:xxxx::xxxx:xxxx:xxxx:xxxx/64",
    "type": "g5-nanode-1",
    "hypervisor": "kvm",
    "disk": 20480
}
```

Hope this helps.

**Comment by lfxc** [comment]
perfect.  thanks you!
