### ISSUE TITLE
Linode API SSL upgrade - library no longer works out of the box 

### ISSUE THREAD

**Issue by leximayfield** [webinarium/linode-api3#7]
This afternoon, the API client stopped working for me.  Apparently, Linode has upgraded its TLS infrastructure and no longer supports TLSv1.0.

I was able to fix the issue by setting the curl option `CURLOPT_SSLVERSION` to `6`.  I did this in both `Batch.php` and `BaseLinodeApi.php`.  However, I only patched my local copy of the library and haven't run extensive tests so I'm unsure about any sort of deeper ramifications.

**Comment by webinarium** [comment]
Thank you for the fix! Those two files are the only places to update, so I just released the new version 1.1.15 with your fix integrated.
